### ISSUE TITLE
[Arcs] [bug] Song of Freedom FAQ misplaced

### ISSUE THREAD

**Issue by turmoilbyrd** [LederCards/cards#91]
Also we just found out something weird

On the [FAQ page](https://cards.ledergames.com/faq?locale=en-US&productId=arcs&q=&d=images&s=name&b=asc&p=0) I can see some entries for Song of Freedom. In two separate entries.
 
![image](https://github.com/user-attachments/assets/05b63bb2-2a5d-4954-a4ca-17201ac85910)

Bugs:
- both links go to the campaign version
- on the Campaign card we only see one entry. Not the 3 entries on the bottom

This is likely again due to naming conflict

**Comment by jdyearsley** [comment]
@seiyria - Apologies if I we already went over this. Is there a way to differentiate FAQ entries between two cards with the same name?

**Comment by seiyria** [comment]
Yes! You can specify the card id in the FAQ rather than the name and it should specifically target that instance of the card. Let me know if that's not the case, but I believe it should work.

**Comment by seiyria** [comment]
Oh, I see. No, in this case there's not. I misread it as linking it. I can add the id to the FAQ page though if that'd help.

**Comment by jdyearsley** [comment]
Would it be possible to format it so that it displays the _product name_ in parentheses?

Like this: "Song of Freedom (Arcs Base Game)" vs. "Song of Freedom (Blighted Reach)"

**Comment by seiyria** [comment]
That might be trickier, but I can look into it. From a quick glance here I can't tell if the data is available where/how I need it to do that.

**Comment by seiyria** [comment]
@jdyearsley https://github.com/LederCards/cards/blob/f5a73d4aa98593a0e018b91f644cba10e0b37f0e/content/faq/arcs/en-US.yml#L84-L85

You can now specify `cardDisplay` (and also, you can specify card by id, rather than name, in case of duplicates). Specifying `cardDisplay` will overwrite the display value of the card (there's not a way to look up by product, I think, sorry!). Also, specifying `card` by `id` will allow you to link to specific instances of cards rather than having to go by name. 

Let me know if this works!

![image](https://github.com/user-attachments/assets/db1a6598-76a1-4933-bbcd-6182ef00c322)

**Comment by jdyearsley** [comment]
Yes, this works perfectly! Thank ya.
